parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}

  strategy:
    matrix:
      Python37:
        python.version: '3.7'

  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'

    - bash: npm install -g yarn
      displayName: "Install Yarn"

    - bash: yarn
      displayName: "Install Deps"

    - script: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
        jupyter labextension install .
        jupyter serverextension enable --py nbcelltests
      displayName: 'Developer install'

    - script:
        make verify-install
      displayName: 'Check everything was installed'

    - script: |
        make lint
      displayName: 'Lint'

    - script:
        make tests
      displayName: 'Test'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: 'python_junit.xml'
        testRunTitle: 'Publish test results for Python $(python.version) $(manylinux_flag)'

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/*coverage.xml'
